/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-06-23 06:18:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.console.task;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.owasp.esapi.ESAPI;

public final class ConfigureOAuth2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "ConfigureOAuth2";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/tags/redirectToXui.tag", Long.valueOf(1581904548000L));
    _jspx_dependants.put("/WEB-INF/jato.tld", Long.valueOf(1581905646000L));
    _jspx_dependants.put("/WEB-INF/com_sun_web_ui/cc.tld", Long.valueOf(1581905646000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.owasp.esapi.ESAPI");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005ffireChildDisplayEvents_005fclassName;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fheader_0026_005fpageTitle_005fname_005ffireDisplayEvents_005fcopyrightYear_005fbundleID;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fform_0026_005fname_005fmethod;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjato_005fhidden_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fprimarymasthead_0026_005fname_005flogoutOnClick_005flocale_005fbundleID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005falertinline_0026_005fname_005fbundleID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fpagetitle_0026_005fviewMenuLabel_005fshowPageTitleSeparator_005fshowPageButtonsTop_005fshowPageButtonsBottom_005fpageTitleHelpMessage_005fname_005fbundleID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fpropertysheet_0026_005fshowJumpLinks_005fname_005fbundleID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fescape_005fdefaultValue_005fbundleID_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005ffireChildDisplayEvents_005fclassName = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fheader_0026_005fpageTitle_005fname_005ffireDisplayEvents_005fcopyrightYear_005fbundleID = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fform_0026_005fname_005fmethod = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjato_005fhidden_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fprimarymasthead_0026_005fname_005flogoutOnClick_005flocale_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005falertinline_0026_005fname_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fpagetitle_0026_005fviewMenuLabel_005fshowPageTitleSeparator_005fshowPageButtonsTop_005fshowPageButtonsBottom_005fpageTitleHelpMessage_005fname_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fpropertysheet_0026_005fshowJumpLinks_005fname_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fescape_005fdefaultValue_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005ffireChildDisplayEvents_005fclassName.release();
    _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005fheader_0026_005fpageTitle_005fname_005ffireDisplayEvents_005fcopyrightYear_005fbundleID.release();
    _005fjspx_005ftagPool_005fcc_005fform_0026_005fname_005fmethod.release();
    _005fjspx_005ftagPool_005fjato_005fhidden_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005fprimarymasthead_0026_005fname_005flogoutOnClick_005flocale_005fbundleID_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005falertinline_0026_005fname_005fbundleID_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005fpagetitle_0026_005fviewMenuLabel_005fshowPageTitleSeparator_005fshowPageButtonsTop_005fshowPageButtonsBottom_005fpageTitleHelpMessage_005fname_005fbundleID_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005fpropertysheet_0026_005fshowJumpLinks_005fname_005fbundleID_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fescape_005fdefaultValue_005fbundleID_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    request.setCharacterEncoding("UTF-8");

      out.write('\n');
      //  jato:useViewBean
      com.iplanet.jato.taglib.UseViewBeanTag _jspx_th_jato_005fuseViewBean_005f0 = (com.iplanet.jato.taglib.UseViewBeanTag) _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005ffireChildDisplayEvents_005fclassName.get(com.iplanet.jato.taglib.UseViewBeanTag.class);
      boolean _jspx_th_jato_005fuseViewBean_005f0_reused = false;
      try {
        _jspx_th_jato_005fuseViewBean_005f0.setPageContext(_jspx_page_context);
        _jspx_th_jato_005fuseViewBean_005f0.setParent(null);
        // /console/task/ConfigureOAuth2.jsp(37,0) name = className type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_jato_005fuseViewBean_005f0.setClassName("com.sun.identity.console.task.ConfigureOAuth2ViewBean");
        // /console/task/ConfigureOAuth2.jsp(37,0) name = fireChildDisplayEvents type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_jato_005fuseViewBean_005f0.setFireChildDisplayEvents("true");
        int _jspx_eval_jato_005fuseViewBean_005f0 = _jspx_th_jato_005fuseViewBean_005f0.doStartTag();
        if (_jspx_eval_jato_005fuseViewBean_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          com.iplanet.jato.view.ContainerView currentContainerView = null;
          com.iplanet.jato.view.TiledView currentTiledView = null;
          com.iplanet.jato.view.TreeView currentTreeView = null;
          com.sun.identity.console.task.ConfigureOAuth2ViewBean viewBean = null;
          currentContainerView = (com.iplanet.jato.view.ContainerView) _jspx_page_context.findAttribute("currentContainerView");
          currentTiledView = (com.iplanet.jato.view.TiledView) _jspx_page_context.findAttribute("currentTiledView");
          currentTreeView = (com.iplanet.jato.view.TreeView) _jspx_page_context.findAttribute("currentTreeView");
          viewBean = (com.sun.identity.console.task.ConfigureOAuth2ViewBean) _jspx_page_context.findAttribute("viewBean");
          do {
            out.write('\n');
            out.write(' ');
            out.write('\n');
            //  cc:i18nbundle
            com.sun.web.ui.taglib.i18n.CCBundleTag _jspx_th_cc_005fi18nbundle_005f0 = (com.sun.web.ui.taglib.i18n.CCBundleTag) _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody.get(com.sun.web.ui.taglib.i18n.CCBundleTag.class);
            boolean _jspx_th_cc_005fi18nbundle_005f0_reused = false;
            try {
              _jspx_th_cc_005fi18nbundle_005f0.setPageContext(_jspx_page_context);
              _jspx_th_cc_005fi18nbundle_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
              // /console/task/ConfigureOAuth2.jsp(41,0) name = baseName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fi18nbundle_005f0.setBaseName("amConsole");
              // /console/task/ConfigureOAuth2.jsp(41,0) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fi18nbundle_005f0.setId("amConsole");
              // /console/task/ConfigureOAuth2.jsp(41,0) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fi18nbundle_005f0.setLocale(((com.sun.identity.console.base.AMViewBeanBase)viewBean).getUserLocale());
              int _jspx_eval_cc_005fi18nbundle_005f0 = _jspx_th_cc_005fi18nbundle_005f0.doStartTag();
              if (_jspx_th_cc_005fi18nbundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody.reuse(_jspx_th_cc_005fi18nbundle_005f0);
              _jspx_th_cc_005fi18nbundle_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fi18nbundle_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fi18nbundle_005f0_reused);
            }
            out.write('\n');
            out.write(' ');
            out.write('\n');
            //  cc:header
            org.forgerock.openam.console.ui.taglib.header.CCHtmlHeaderTag _jspx_th_cc_005fheader_005f0 = (org.forgerock.openam.console.ui.taglib.header.CCHtmlHeaderTag) _005fjspx_005ftagPool_005fcc_005fheader_0026_005fpageTitle_005fname_005ffireDisplayEvents_005fcopyrightYear_005fbundleID.get(org.forgerock.openam.console.ui.taglib.header.CCHtmlHeaderTag.class);
            boolean _jspx_th_cc_005fheader_005f0_reused = false;
            try {
              _jspx_th_cc_005fheader_005f0.setPageContext(_jspx_page_context);
              _jspx_th_cc_005fheader_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
              // /console/task/ConfigureOAuth2.jsp(44,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fheader_005f0.setName("hdrCommon");
              // /console/task/ConfigureOAuth2.jsp(44,0) name = pageTitle type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fheader_005f0.setPageTitle("webconsole.title");
              // /console/task/ConfigureOAuth2.jsp(44,0) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fheader_005f0.setBundleID("amConsole");
              // /console/task/ConfigureOAuth2.jsp(44,0) name = copyrightYear type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fheader_005f0.setCopyrightYear("2008");
              // /console/task/ConfigureOAuth2.jsp(44,0) name = fireDisplayEvents type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fheader_005f0.setFireDisplayEvents("true");
              int _jspx_eval_cc_005fheader_005f0 = _jspx_th_cc_005fheader_005f0.doStartTag();
              if (_jspx_eval_cc_005fheader_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspx_eval_cc_005fheader_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_cc_005fheader_005f0);
                }
                do {
                  out.write("\n");
                  out.write(" \n");
                  out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"../console/css/openam.css\" />\n");
                  out.write("   <script language=\"javascript\" src=\"../console/js/am.js\"></script>\n");
                  out.write("   <script language=\"javascript\" src=\"../console/js/tasksPage.js\"></script>\n");
                  out.write("   <script language=\"javascript\" src=\"../com_sun_web_ui/js/dynamic.js\"></script>\n");
                  out.write(" \n");
                  out.write("   <div id=\"main\" style=\"position: absolute; margin: 0; border: none; padding: 0; width:auto; height:101%;\">\n");
                  out.write("   <div id=\"divhelp\" style=\"display: none; position:absolute; margin: 0; border: 1px solid #AABCC8; padding: 0; width:400px; height:200px; background:#FCFCFC\">\n");
                  out.write("       <table border=0 cellpadding=2 cellspacing=0 width=\"100%\">\n");
                  out.write("           <tr><td width=99%><span id=\"divHelpmsg\" /></td>\n");
                  out.write("               <td width=\"1%\" valign=\"top\">\n");
                  out.write("                   <img src=\"../console/images/tasks/close.gif\" width=\"16\" height=\"16\" onClick=\"hideHelp()\" />\n");
                  out.write("               </td>\n");
                  out.write("           </tr>\n");
                  out.write("       </table>\n");
                  out.write("   </div>\n");
                  out.write(" \n");
                  out.write("   ");
                  //  cc:form
                  org.forgerock.openam.console.ui.taglib.AutoCCFormTag _jspx_th_cc_005fform_005f0 = (org.forgerock.openam.console.ui.taglib.AutoCCFormTag) _005fjspx_005ftagPool_005fcc_005fform_0026_005fname_005fmethod.get(org.forgerock.openam.console.ui.taglib.AutoCCFormTag.class);
                  boolean _jspx_th_cc_005fform_005f0_reused = false;
                  try {
                    _jspx_th_cc_005fform_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_cc_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fheader_005f0);
                    // /console/task/ConfigureOAuth2.jsp(62,3) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_cc_005fform_005f0.setName("ConfigureOAuth2");
                    // /console/task/ConfigureOAuth2.jsp(62,3) name = method type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_cc_005fform_005f0.setMethod("post");
                    int _jspx_eval_cc_005fform_005f0 = _jspx_th_cc_005fform_005f0.doStartTag();
                    if (_jspx_eval_cc_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      if (_jspx_eval_cc_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_cc_005fform_005f0);
                      }
                      do {
                        out.write("\n");
                        out.write("       ");
                        if (_jspx_meth_jato_005fhidden_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
                          return;
                        out.write("\n");
                        out.write("       <script language=\"javascript\">\n");
                        out.write("           function confirmLogout() {\n");
                        out.write("               return confirm(\"");
                        if (_jspx_meth_cc_005ftext_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
                          return;
                        out.write("\");\n");
                        out.write("           }\n");
                        out.write(" \n");
                        out.write("           function cancelOp() {\n");
                        out.write("               redirectToXui();\n");
                        out.write("               return false;\n");
                        out.write("           }\n");
                        out.write(" \n");
                        out.write("       </script>\n");
                        out.write(" \n");
                        out.write("       ");
                        //  cc:primarymasthead
                        org.forgerock.openam.console.ui.taglib.masthead.CCPrimaryMastheadTag _jspx_th_cc_005fprimarymasthead_005f0 = (org.forgerock.openam.console.ui.taglib.masthead.CCPrimaryMastheadTag) _005fjspx_005ftagPool_005fcc_005fprimarymasthead_0026_005fname_005flogoutOnClick_005flocale_005fbundleID_005fnobody.get(org.forgerock.openam.console.ui.taglib.masthead.CCPrimaryMastheadTag.class);
                        boolean _jspx_th_cc_005fprimarymasthead_005f0_reused = false;
                        try {
                          _jspx_th_cc_005fprimarymasthead_005f0.setPageContext(_jspx_page_context);
                          _jspx_th_cc_005fprimarymasthead_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
                          // /console/task/ConfigureOAuth2.jsp(76,7) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_cc_005fprimarymasthead_005f0.setName("mhCommon");
                          // /console/task/ConfigureOAuth2.jsp(76,7) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_cc_005fprimarymasthead_005f0.setBundleID("amConsole");
                          // /console/task/ConfigureOAuth2.jsp(76,7) name = logoutOnClick type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_cc_005fprimarymasthead_005f0.setLogoutOnClick("return confirmLogout();");
                          // /console/task/ConfigureOAuth2.jsp(76,7) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_cc_005fprimarymasthead_005f0.setLocale(((com.sun.identity.console.base.AMViewBeanBase)viewBean).getUserLocale());
                          int _jspx_eval_cc_005fprimarymasthead_005f0 = _jspx_th_cc_005fprimarymasthead_005f0.doStartTag();
                          if (_jspx_th_cc_005fprimarymasthead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fcc_005fprimarymasthead_0026_005fname_005flogoutOnClick_005flocale_005fbundleID_005fnobody.reuse(_jspx_th_cc_005fprimarymasthead_005f0);
                          _jspx_th_cc_005fprimarymasthead_005f0_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fprimarymasthead_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fprimarymasthead_005f0_reused);
                        }
                        out.write("\n");
                        out.write("       <table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"100%\">\n");
                        out.write("           <tr>\n");
                        out.write("               <td>\n");
                        out.write("                   ");
                        if (_jspx_meth_cc_005falertinline_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
                          return;
                        out.write("\n");
                        out.write("               </td>\n");
                        out.write("           </tr>\n");
                        out.write("       </table>\n");
                        out.write(" \n");
                        out.write("       ");
                        out.write("\n");
                        out.write("       ");
                        if (_jspx_meth_cc_005fpagetitle_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
                          return;
                        out.write("\n");
                        out.write(" \n");
                        out.write("       ");
                        if (_jspx_meth_cc_005fpropertysheet_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
                          return;
                        out.write("\n");
                        out.write(" \n");
                        out.write("   ");
                        int evalDoAfterBody = _jspx_th_cc_005fform_005f0.doAfterBody();
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                      if (_jspx_eval_cc_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = _jspx_page_context.popBody();
                      }
                    }
                    if (_jspx_th_cc_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fcc_005fform_0026_005fname_005fmethod.reuse(_jspx_th_cc_005fform_005f0);
                    _jspx_th_cc_005fform_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fform_005f0_reused);
                  }
                  out.write('\n');
                  int evalDoAfterBody = _jspx_th_cc_005fheader_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_cc_005fheader_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_cc_005fheader_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fcc_005fheader_0026_005fpageTitle_005fname_005ffireDisplayEvents_005fcopyrightYear_005fbundleID.reuse(_jspx_th_cc_005fheader_005f0);
              _jspx_th_cc_005fheader_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fheader_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fheader_005f0_reused);
            }
            out.write("\n");
            out.write("</div>\n");
            out.write("<div id=\"dlg\" class=\"dvs\"></div>\n");
            out.write(" \n");
            if (_jspx_meth_console_005fredirectToXui_005f0(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("\n");
            out.write("<script language=\"javascript\">\n");
            out.write("var msgCreating = \"<p><img src=\\\"../console/images/processing.gif\\\" width=\\\"66\\\" height\\\"66\\\"/></p>");
            if (_jspx_meth_cc_005ftext_005f1(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write("\";\n");
            out.write("var ttlCreated = \"<h3>");
            if (_jspx_meth_cc_005ftext_005f2(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write("</h3>\";\n");
            out.write("var msgCreated = \"<p>&nbsp;</p><input name=\\\"btnOK\\\" type=\\\"submit\\\" class=\\\"Btn1\\\" value=\\\"");
            if (_jspx_meth_cc_005ftext_005f3(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write("\\\" onClick=\\\"redirectToXui();return false;\\\" /></div></p>\";\n");
            out.write("var closeBtn = \"<p>&nbsp;</p><p><div class=\\\"TtlBtnDiv\\\"><input name=\\\"btnClose\\\" type=\\\"submit\\\" class=\\\"Btn1\\\" value=\\\"");
            if (_jspx_meth_cc_005ftext_005f4(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write("\\\" onClick=\\\"focusMain();return false;\\\" /></div></p>\";\n");
            out.write(" \n");
            out.write("var frm = document.forms['ConfigureOAuth2'];\n");
            out.write("var btn1 = frm.elements['ConfigureOAuth2.button1'];\n");
            out.write("btn1.onclick = submitPage;\n");
            out.write("var btn2 = frm.elements['ConfigureOAuth2.button2'];\n");
            out.write("btn2.onclick = cancelOp;\n");
            out.write("var ajaxObj = getXmlHttpRequestObject();\n");
            out.write("var userLocale = \"");
            out.print( viewBean.getUserLocale().toString() );
            out.write('"');
            out.write(';');
            out.write('\n');

   String type = request.getParameter("type");
   if (!ESAPI.validator().isValidInput("Social AuthN Type", type, "HTTPParameterValue", 2000, true)) {
       type = null;
   }
   if (type != null) {
       out.println("var type = \"" + ESAPI.encoder().encodeForHTML(type) + "\";");
   } else {
       out.println("var type = null;");
   }

            out.write("\n");
            out.write("\n");
            out.write("function getData(){\n");
            out.write("   var realm = frm.elements['ConfigureOAuth2.tfRealm'].value;\n");
            out.write("   var rtl = frm.elements['ConfigureOAuth2.choiceRefreshLifetime'].value;\n");
            out.write("   var acl = frm.elements['ConfigureOAuth2.choiceCodeLifetime'].value;\n");
            out.write("   var atl = frm.elements['ConfigureOAuth2.choiceTokenLifetime'].value;\n");
            out.write("   var irt = (frm.elements['ConfigureOAuth2.choiceRefreshToken'].checked == true) ? \"true\" : \"false\";\n");
            out.write("   var irtr = (frm.elements['ConfigureOAuth2.choiceRefreshTokenOnRefreshing'].checked == true) ? \"true\" : \"false\";\n");
            out.write("   var sic = frm.elements['ConfigureOAuth2.choiceScopeImpl'].value;\n");
            out.write("   return \"&realm=\" + escapeEx(realm) +\n");
            out.write("           \"&type=\" + escapeEx(type) +\n");
            out.write("           \"&rtl=\" + escapeEx(rtl) +\n");
            out.write("           \"&acl=\" + escapeEx(acl) +\n");
            out.write("           \"&atl=\" + escapeEx(atl) +\n");
            out.write("           \"&irt=\" + escapeEx(irt) +\n");
            out.write("           \"&irtr=\" + escapeEx(irtr) +\n");
            out.write("           \"&sic=\" + escapeEx(sic);\n");
            out.write("}\n");
            out.write(" \n");
            out.write("function submitPage() {\n");
            out.write("   document.getElementById('dlg').style.top = '300px';\n");
            out.write("   fade();\n");
            out.write("   document.getElementById('dlg').innerHTML = '<center>' +\n");
            out.write("           msgCreating + '</center>';\n");
            out.write("   var url = \"../console/ajax/AjaxProxy.jsp\";\n");
            out.write("   var params = 'locale=' + userLocale +\n");
            out.write("           '&class=com.sun.identity.workflow.ConfigureOAuth2' + getData();\n");
            out.write("   ajaxPost(ajaxObj, url, params, configured);\n");
            out.write("   return false;\n");
            out.write("}\n");
            out.write(" \n");
            out.write("function configured() {\n");
            out.write("   if (ajaxObj.readyState == 4) {\n");
            out.write("       var result = hexToString(ajaxObj.responseText);\n");
            out.write("       var status = result.substring(0, result.indexOf('|'));\n");
            out.write("       var result = result.substring(result.indexOf('|') +1);\n");
            out.write("       var msg = '<center><p>' + result + '</p></center>';\n");
            out.write("       if (status == 0) {\n");
            out.write("           msg = '<center>' + ttlCreated + msg + msgCreated + '</center>';\n");
            out.write("       } else {\n");
            out.write("           msg = msg + '<center>' +  closeBtn + '</center>';\n");
            out.write("       }\n");
            out.write("       document.getElementById('dlg').innerHTML = msg;\n");
            out.write("   }\n");
            out.write("}\n");
            out.write("\n");
            out.write("</script>\n");
            int evalDoAfterBody = _jspx_th_jato_005fuseViewBean_005f0.doAfterBody();
            currentContainerView = (com.iplanet.jato.view.ContainerView) _jspx_page_context.findAttribute("currentContainerView");
            currentTiledView = (com.iplanet.jato.view.TiledView) _jspx_page_context.findAttribute("currentTiledView");
            currentTreeView = (com.iplanet.jato.view.TreeView) _jspx_page_context.findAttribute("currentTreeView");
            viewBean = (com.sun.identity.console.task.ConfigureOAuth2ViewBean) _jspx_page_context.findAttribute("viewBean");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_jato_005fuseViewBean_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005ffireChildDisplayEvents_005fclassName.reuse(_jspx_th_jato_005fuseViewBean_005f0);
        _jspx_th_jato_005fuseViewBean_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005fuseViewBean_005f0, _jsp_getInstanceManager(), _jspx_th_jato_005fuseViewBean_005f0_reused);
      }
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jato_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jato:hidden
    com.iplanet.jato.taglib.html.HiddenTag _jspx_th_jato_005fhidden_005f0 = (com.iplanet.jato.taglib.html.HiddenTag) _005fjspx_005ftagPool_005fjato_005fhidden_0026_005fname_005fnobody.get(com.iplanet.jato.taglib.html.HiddenTag.class);
    boolean _jspx_th_jato_005fhidden_005f0_reused = false;
    try {
      _jspx_th_jato_005fhidden_005f0.setPageContext(_jspx_page_context);
      _jspx_th_jato_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/task/ConfigureOAuth2.jsp(63,7) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_jato_005fhidden_005f0.setName("szCache");
      int _jspx_eval_jato_005fhidden_005f0 = _jspx_th_jato_005fhidden_005f0.doStartTag();
      if (_jspx_th_jato_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fjato_005fhidden_0026_005fname_005fnobody.reuse(_jspx_th_jato_005fhidden_005f0);
      _jspx_th_jato_005fhidden_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005fhidden_005f0, _jsp_getInstanceManager(), _jspx_th_jato_005fhidden_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005ftext_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:text
    com.sun.web.ui.taglib.html.CCStaticTextFieldTag _jspx_th_cc_005ftext_005f0 = (com.sun.web.ui.taglib.html.CCStaticTextFieldTag) _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.html.CCStaticTextFieldTag.class);
    boolean _jspx_th_cc_005ftext_005f0_reused = false;
    try {
      _jspx_th_cc_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005ftext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/task/ConfigureOAuth2.jsp(66,31) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f0.setName("txtLogout");
      // /console/task/ConfigureOAuth2.jsp(66,31) name = defaultValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f0.setDefaultValue("masthead.logoutMessage");
      // /console/task/ConfigureOAuth2.jsp(66,31) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f0.setBundleID("amConsole");
      int _jspx_eval_cc_005ftext_005f0 = _jspx_th_cc_005ftext_005f0.doStartTag();
      if (_jspx_th_cc_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody.reuse(_jspx_th_cc_005ftext_005f0);
      _jspx_th_cc_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005falertinline_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:alertinline
    com.sun.web.ui.taglib.alert.CCAlertInlineTag _jspx_th_cc_005falertinline_005f0 = (com.sun.web.ui.taglib.alert.CCAlertInlineTag) _005fjspx_005ftagPool_005fcc_005falertinline_0026_005fname_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.alert.CCAlertInlineTag.class);
    boolean _jspx_th_cc_005falertinline_005f0_reused = false;
    try {
      _jspx_th_cc_005falertinline_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005falertinline_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/task/ConfigureOAuth2.jsp(80,19) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005falertinline_005f0.setName("ialertCommon");
      // /console/task/ConfigureOAuth2.jsp(80,19) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005falertinline_005f0.setBundleID("amConsole");
      int _jspx_eval_cc_005falertinline_005f0 = _jspx_th_cc_005falertinline_005f0.doStartTag();
      if (_jspx_th_cc_005falertinline_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005falertinline_0026_005fname_005fbundleID_005fnobody.reuse(_jspx_th_cc_005falertinline_005f0);
      _jspx_th_cc_005falertinline_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005falertinline_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005falertinline_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005fpagetitle_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:pagetitle
    com.sun.web.ui.taglib.pagetitle.CCPageTitleTag _jspx_th_cc_005fpagetitle_005f0 = (com.sun.web.ui.taglib.pagetitle.CCPageTitleTag) _005fjspx_005ftagPool_005fcc_005fpagetitle_0026_005fviewMenuLabel_005fshowPageTitleSeparator_005fshowPageButtonsTop_005fshowPageButtonsBottom_005fpageTitleHelpMessage_005fname_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.pagetitle.CCPageTitleTag.class);
    boolean _jspx_th_cc_005fpagetitle_005f0_reused = false;
    try {
      _jspx_th_cc_005fpagetitle_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005fpagetitle_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/task/ConfigureOAuth2.jsp(86,7) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setName("pgtitle");
      // /console/task/ConfigureOAuth2.jsp(86,7) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setBundleID("amConsole");
      // /console/task/ConfigureOAuth2.jsp(86,7) name = showPageTitleSeparator type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setShowPageTitleSeparator("true");
      // /console/task/ConfigureOAuth2.jsp(86,7) name = viewMenuLabel type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setViewMenuLabel("");
      // /console/task/ConfigureOAuth2.jsp(86,7) name = pageTitleHelpMessage type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setPageTitleHelpMessage("");
      // /console/task/ConfigureOAuth2.jsp(86,7) name = showPageButtonsTop type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setShowPageButtonsTop("true");
      // /console/task/ConfigureOAuth2.jsp(86,7) name = showPageButtonsBottom type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setShowPageButtonsBottom("false");
      int _jspx_eval_cc_005fpagetitle_005f0 = _jspx_th_cc_005fpagetitle_005f0.doStartTag();
      if (_jspx_th_cc_005fpagetitle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005fpagetitle_0026_005fviewMenuLabel_005fshowPageTitleSeparator_005fshowPageButtonsTop_005fshowPageButtonsBottom_005fpageTitleHelpMessage_005fname_005fbundleID_005fnobody.reuse(_jspx_th_cc_005fpagetitle_005f0);
      _jspx_th_cc_005fpagetitle_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fpagetitle_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fpagetitle_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005fpropertysheet_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:propertysheet
    org.forgerock.openam.console.ui.taglib.propertysheet.CCPropertySheetTag _jspx_th_cc_005fpropertysheet_005f0 = (org.forgerock.openam.console.ui.taglib.propertysheet.CCPropertySheetTag) _005fjspx_005ftagPool_005fcc_005fpropertysheet_0026_005fshowJumpLinks_005fname_005fbundleID_005fnobody.get(org.forgerock.openam.console.ui.taglib.propertysheet.CCPropertySheetTag.class);
    boolean _jspx_th_cc_005fpropertysheet_005f0_reused = false;
    try {
      _jspx_th_cc_005fpropertysheet_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005fpropertysheet_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/task/ConfigureOAuth2.jsp(88,7) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpropertysheet_005f0.setName("propertyAttributes");
      // /console/task/ConfigureOAuth2.jsp(88,7) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpropertysheet_005f0.setBundleID("amConsole");
      // /console/task/ConfigureOAuth2.jsp(88,7) name = showJumpLinks type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpropertysheet_005f0.setShowJumpLinks("false");
      int _jspx_eval_cc_005fpropertysheet_005f0 = _jspx_th_cc_005fpropertysheet_005f0.doStartTag();
      if (_jspx_th_cc_005fpropertysheet_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005fpropertysheet_0026_005fshowJumpLinks_005fname_005fbundleID_005fnobody.reuse(_jspx_th_cc_005fpropertysheet_005f0);
      _jspx_th_cc_005fpropertysheet_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fpropertysheet_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fpropertysheet_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_console_005fredirectToXui_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  console:redirectToXui
    org.apache.jsp.tag.web.redirectToXui_tag _jspx_th_console_005fredirectToXui_005f0 = new org.apache.jsp.tag.web.redirectToXui_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_console_005fredirectToXui_005f0);
    try {
      _jspx_th_console_005fredirectToXui_005f0.setJspContext(_jspx_page_context);
      _jspx_th_console_005fredirectToXui_005f0.setParent(_jspx_th_jato_005fuseViewBean_005f0);
      // /console/task/ConfigureOAuth2.jsp(95,0) name = realm type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_console_005fredirectToXui_005f0.setRealm("encodeURIComponent(frm.elements['ConfigureOAuth2.tfRealm'].value)");
      // /console/task/ConfigureOAuth2.jsp(95,0) name = xuiPath type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_console_005fredirectToXui_005f0.setXuiPath("../XUI{authRealm}#realms/{realm}/dashboard");
      _jspx_th_console_005fredirectToXui_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_console_005fredirectToXui_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005ftext_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:text
    com.sun.web.ui.taglib.html.CCStaticTextFieldTag _jspx_th_cc_005ftext_005f1 = (com.sun.web.ui.taglib.html.CCStaticTextFieldTag) _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fescape_005fdefaultValue_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.html.CCStaticTextFieldTag.class);
    boolean _jspx_th_cc_005ftext_005f1_reused = false;
    try {
      _jspx_th_cc_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_cc_005ftext_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
      // /console/task/ConfigureOAuth2.jsp(99,99) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f1.setName("txtConfiguring");
      // /console/task/ConfigureOAuth2.jsp(99,99) name = defaultValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f1.setDefaultValue("configuring.oauth2.waiting");
      // /console/task/ConfigureOAuth2.jsp(99,99) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f1.setBundleID("amConsole");
      // /console/task/ConfigureOAuth2.jsp(99,99) name = escape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f1.setEscape("false");
      int _jspx_eval_cc_005ftext_005f1 = _jspx_th_cc_005ftext_005f1.doStartTag();
      if (_jspx_th_cc_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fescape_005fdefaultValue_005fbundleID_005fnobody.reuse(_jspx_th_cc_005ftext_005f1);
      _jspx_th_cc_005ftext_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005ftext_005f1, _jsp_getInstanceManager(), _jspx_th_cc_005ftext_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005ftext_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:text
    com.sun.web.ui.taglib.html.CCStaticTextFieldTag _jspx_th_cc_005ftext_005f2 = (com.sun.web.ui.taglib.html.CCStaticTextFieldTag) _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fescape_005fdefaultValue_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.html.CCStaticTextFieldTag.class);
    boolean _jspx_th_cc_005ftext_005f2_reused = false;
    try {
      _jspx_th_cc_005ftext_005f2.setPageContext(_jspx_page_context);
      _jspx_th_cc_005ftext_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
      // /console/task/ConfigureOAuth2.jsp(100,22) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f2.setName("txtTtlCreated");
      // /console/task/ConfigureOAuth2.jsp(100,22) name = defaultValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f2.setDefaultValue("oauth2.configured.title");
      // /console/task/ConfigureOAuth2.jsp(100,22) name = escape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f2.setEscape("false");
      // /console/task/ConfigureOAuth2.jsp(100,22) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f2.setBundleID("amConsole");
      int _jspx_eval_cc_005ftext_005f2 = _jspx_th_cc_005ftext_005f2.doStartTag();
      if (_jspx_th_cc_005ftext_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fescape_005fdefaultValue_005fbundleID_005fnobody.reuse(_jspx_th_cc_005ftext_005f2);
      _jspx_th_cc_005ftext_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005ftext_005f2, _jsp_getInstanceManager(), _jspx_th_cc_005ftext_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005ftext_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:text
    com.sun.web.ui.taglib.html.CCStaticTextFieldTag _jspx_th_cc_005ftext_005f3 = (com.sun.web.ui.taglib.html.CCStaticTextFieldTag) _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.html.CCStaticTextFieldTag.class);
    boolean _jspx_th_cc_005ftext_005f3_reused = false;
    try {
      _jspx_th_cc_005ftext_005f3.setPageContext(_jspx_page_context);
      _jspx_th_cc_005ftext_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
      // /console/task/ConfigureOAuth2.jsp(101,92) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f3.setName("txtOKBtn");
      // /console/task/ConfigureOAuth2.jsp(101,92) name = defaultValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f3.setDefaultValue("ajax.ok.button");
      // /console/task/ConfigureOAuth2.jsp(101,92) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f3.setBundleID("amConsole");
      int _jspx_eval_cc_005ftext_005f3 = _jspx_th_cc_005ftext_005f3.doStartTag();
      if (_jspx_th_cc_005ftext_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody.reuse(_jspx_th_cc_005ftext_005f3);
      _jspx_th_cc_005ftext_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005ftext_005f3, _jsp_getInstanceManager(), _jspx_th_cc_005ftext_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005ftext_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:text
    com.sun.web.ui.taglib.html.CCStaticTextFieldTag _jspx_th_cc_005ftext_005f4 = (com.sun.web.ui.taglib.html.CCStaticTextFieldTag) _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.html.CCStaticTextFieldTag.class);
    boolean _jspx_th_cc_005ftext_005f4_reused = false;
    try {
      _jspx_th_cc_005ftext_005f4.setPageContext(_jspx_page_context);
      _jspx_th_cc_005ftext_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
      // /console/task/ConfigureOAuth2.jsp(102,121) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f4.setName("txtCloseBtn");
      // /console/task/ConfigureOAuth2.jsp(102,121) name = defaultValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f4.setDefaultValue("ajax.close.button");
      // /console/task/ConfigureOAuth2.jsp(102,121) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f4.setBundleID("amConsole");
      int _jspx_eval_cc_005ftext_005f4 = _jspx_th_cc_005ftext_005f4.doStartTag();
      if (_jspx_th_cc_005ftext_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody.reuse(_jspx_th_cc_005ftext_005f4);
      _jspx_th_cc_005ftext_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005ftext_005f4, _jsp_getInstanceManager(), _jspx_th_cc_005ftext_005f4_reused);
    }
    return false;
  }
}
